// Runs the real validator against fixture lockfile pairs and a stubbed
// registry. The suite's failure mode is a false pass — a fixture that stops
// matching the rule it names still goes green — so the accepting cases
// assert the parse found the changes they claim, not just `ok`.

import { test } from "node:test";
import assert from "node:assert/strict";
import { CRATES_IO_SOURCE } from "./update-lockfile.mjs";
import {
  soundnessFailures,
  validateLockfileUpdate,
  verifyUpstream,
} from "./check-rust-update.mjs";
import { parseLockfile } from "./update-lockfile.mjs";

const renderLock = (packages, { version = 4, extra = "" } = {}) => {
  let out =
    "# This file is automatically @generated by Cargo.\n" +
    "# It is not intended for manual editing.\n" +
    `version = ${version}\n`;
  for (const p of packages) {
    out += `\n[[package]]\nname = "${p.name}"\nversion = "${p.version}"\n`;
    if (p.source !== undefined && p.source !== null) out += `source = "${p.source}"\n`;
    if (p.checksum !== undefined) out += `checksum = "${p.checksum}"\n`;
    else if (p.source !== undefined && p.source !== null) out += `checksum = "c-${p.name}-${p.version}"\n`;
    if (p.deps !== undefined && p.deps.length > 0) {
      out += "dependencies = [\n";
      for (const d of p.deps) out += ` "${d}",\n`;
      out += "]\n";
    }
  }
  return out + extra;
};

const reg = (p) => ({ source: CRATES_IO_SOURCE, ...p });
const APP = { name: "app", version: "0.0.0", deps: ["a"] };

// ---------------------------------------------------------------------------
// Structural validation.
// ---------------------------------------------------------------------------

test("a plain in-range upgrade with a moving checksum passes", () => {
  const result = validateLockfileUpdate(
    renderLock([APP, reg({ name: "a", version: "1.2.0" })]),
    renderLock([APP, reg({ name: "a", version: "1.2.5" })]),
  );
  assert.deepEqual(result.errors, []);
  assert.ok(result.ok);
  assert.deepEqual(result.changes, [
    { name: "a", from: "1.2.0", to: "1.2.5", checksum: "c-a-1.2.5", deps: [] },
  ]);
});

test("reference disambiguation is form, not identity: versioned refs still pass", () => {
  // syn moves within its major while a second major coexists; every
  // dependent's reference respells, but no dependency name moved.
  const before = renderLock([
    { name: "app", version: "0.0.0", deps: ["a", "syn 3.0.2"] },
    reg({ name: "a", version: "1.0.0", deps: ["syn 2.0.119"] }),
    reg({ name: "syn", version: "2.0.119" }),
    reg({ name: "syn", version: "3.0.2" }),
  ]);
  const after = renderLock([
    { name: "app", version: "0.0.0", deps: ["a", "syn 3.0.2"] },
    reg({ name: "a", version: "1.0.0", deps: ["syn 2.0.120"] }),
    reg({ name: "syn", version: "2.0.120" }),
    reg({ name: "syn", version: "3.0.2" }),
  ]);
  const result = validateLockfileUpdate(before, after);
  assert.deepEqual(result.errors, []);
  assert.deepEqual(result.changes.map((c) => `${c.name} ${c.from}->${c.to}`), ["syn 2.0.119->2.0.120"]);
});

test("renamed path dependencies at compatible versions pass validation", () => {
  // Two sourceless path packages share a name at compatible versions —
  // path deps pin exactly, with no range for the resolver to unify — and
  // an ordinary registry change beside them must still validate.
  const at = (a) =>
    renderLock([
      { name: "app", version: "0.0.0", deps: ["foo 1.2.0", "foo 1.3.0", "a"] },
      { name: "foo", version: "1.2.0" },
      { name: "foo", version: "1.3.0" },
      reg({ name: "a", version: a }),
    ]);
  const result = validateLockfileUpdate(at("1.2.0"), at("1.2.5"));
  assert.deepEqual(result.errors, []);
  assert.ok(result.ok);
  assert.deepEqual(result.changes.map((c) => `${c.name} ${c.from}->${c.to}`), ["a 1.2.0->1.2.5"]);
});

test("a version move hiding behind a same-name path sibling is still caught", () => {
  // With one name at two versions, a by-name member map would keep only
  // one instance and let the other move unexamined.
  const at = (second) =>
    renderLock([
      { name: "app", version: "0.0.0", deps: ["foo 1.2.0", `foo ${second}`] },
      { name: "foo", version: "1.2.0" },
      { name: "foo", version: second },
    ]);
  const result = validateLockfileUpdate(at("1.3.0"), at("1.4.0"));
  assert.equal(result.ok, false);
  assert.ok(result.errors.some((e) => /workspace package foo moved 1\.3\.0/.test(e)));
});

test("the preamble, format version, and extra sections are pinned", () => {
  const before = renderLock([APP, reg({ name: "a", version: "1.2.0" })]);
  const cases = [
    [before.replace("version = 4", "version = 3"), /format version changed/],
    [before.replace("# It is not intended", "# Edited"), /preamble changed/],
    [before + '\n[[patch.unused]]\nname = "x"\nversion = "1.0.0"\n', /non-\[\[package\]\] section/],
  ];
  for (const [mutated, message] of cases) {
    const result = validateLockfileUpdate(before, mutated);
    assert.ok(!result.ok);
    assert.match(result.errors.join("\n"), message, String(message));
  }
});

test("the workspace's own packages are untouchable", () => {
  const before = renderLock([APP, reg({ name: "a", version: "1.2.0" })]);
  const cases = [
    [
      renderLock([{ ...APP, version: "0.1.0" }, reg({ name: "a", version: "1.2.0" })]),
      /version comes from a manifest/,
    ],
    [
      renderLock([{ ...APP, deps: ["a", "sneaky"] }, reg({ name: "a", version: "1.2.0" }), reg({ name: "sneaky", version: "1.0.0" })]),
      /changed what it depends on/,
    ],
    [renderLock([reg({ name: "a", version: "1.2.0" })]), /no workspace packages|vanished/],
    [
      renderLock([APP, { name: "app2", version: "0.0.0", deps: ["a"] }, reg({ name: "a", version: "1.2.0" })]),
      /appeared/,
    ],
  ];
  for (const [mutated, message] of cases) {
    const result = validateLockfileUpdate(before, mutated);
    assert.ok(!result.ok);
    assert.match(result.errors.join("\n"), message, String(message));
  }
});

test("a dependency edge crossing a compatibility boundary is refused", () => {
  const result = validateLockfileUpdate(
    renderLock([
      APP,
      reg({ name: "a", version: "1.2.0", deps: ["b"] }),
      reg({ name: "b", version: "1.4.0" }),
    ]),
    renderLock([
      APP,
      reg({ name: "a", version: "1.3.0", deps: ["b"] }),
      reg({ name: "b", version: "2.0.1" }),
    ]),
  );
  assert.ok(!result.ok);
  assert.match(result.errors.join("\n"), /a's edge to b crossed from 1\.4\.0 to 2\.0\.1/);
});

test("a crossing hidden behind a surviving old major is still refused", () => {
  // Another dependent keeps b 1.x alive, so no compat group vanishes — the
  // paired-add/remove reading would pass this; the per-edge rule must not.
  const result = validateLockfileUpdate(
    renderLock([
      { name: "app", version: "0.0.0", deps: ["a", "keeper"] },
      reg({ name: "a", version: "1.2.0", deps: ["b 1.4.0"] }),
      reg({ name: "keeper", version: "3.1.0", deps: ["b 1.4.0"] }),
      reg({ name: "b", version: "1.4.0" }),
    ]),
    renderLock([
      { name: "app", version: "0.0.0", deps: ["a", "keeper"] },
      reg({ name: "a", version: "1.3.0", deps: ["b 2.0.1"] }),
      reg({ name: "keeper", version: "3.1.0", deps: ["b 1.4.0"] }),
      reg({ name: "b", version: "1.4.0" }),
      reg({ name: "b", version: "2.0.1" }),
    ]),
  );
  assert.ok(!result.ok);
  assert.match(result.errors.join("\n"), /a's edge to b crossed from 1\.4\.0 to 2\.0\.1/);
});

test("dual renamed edges to one crate pass, and a crossing among them is refused", () => {
  // One package holds edges to b 1.x AND b 2.x at once (renamed
  // dependencies). Unchanged dual edges beside an unrelated move must
  // pass; the b 2.x edge moving to 3.x while 1.x stays must not.
  const dual = (other, bTwo, bTwoVer) =>
    renderLock([
      { name: "app", version: "0.0.0", deps: ["a", "other"] },
      reg({ name: "a", version: "1.0.0", deps: ["b 1.0.0", `b ${bTwoVer}`] }),
      reg({ name: "b", version: "1.0.0" }),
      reg({ name: "b", version: bTwoVer }),
      reg({ name: "other", version: other }),
    ]);
  const fine = validateLockfileUpdate(dual("3.1.0", 2, "2.0.0"), dual("3.2.0", 2, "2.0.0"));
  assert.deepEqual(fine.errors, []);
  assert.deepEqual(fine.changes.map((c) => c.name), ["other"]);
  const crossed = validateLockfileUpdate(dual("3.1.0", 2, "2.0.0"), dual("3.1.0", 3, "3.0.0"));
  assert.ok(!crossed.ok);
  assert.match(crossed.errors.join("\n"), /a's edge to b crossed from 2\.0\.0 to 3\.0\.0/);
});

test("an arrival alone and a departure alone are legitimate consequences", () => {
  const result = validateLockfileUpdate(
    renderLock([
      APP,
      reg({ name: "a", version: "1.2.0", deps: ["dropped"] }),
      reg({ name: "dropped", version: "0.3.1" }),
    ]),
    renderLock([
      APP,
      reg({ name: "a", version: "1.3.0", deps: ["gained"] }),
      reg({ name: "gained", version: "0.7.2" }),
    ]),
  );
  assert.deepEqual(result.errors, []);
  assert.deepEqual(result.added.map((p) => p.name), ["gained"]);
  assert.deepEqual(result.removed.map((p) => p.name), ["dropped"]);
});

test("downgrades, kept checksums, and pre-releases are refused", () => {
  const at = (v, checksum) => renderLock([APP, reg({ name: "a", version: v, ...(checksum ? { checksum } : {}) })]);
  const cases = [
    [at("1.2.5"), at("1.2.0"), /not an upgrade/],
    [at("1.2.0"), at("1.2.5", "c-a-1.2.0"), /kept its checksum/],
    [at("1.2.0"), at("1.3.0-rc.1"), /pre-release/],
  ];
  for (const [before, after, message] of cases) {
    const result = validateLockfileUpdate(before, after);
    assert.ok(!result.ok);
    assert.match(result.errors.join("\n"), message, String(message));
  }
});

test("a moved package from a source that is not crates.io is refused", () => {
  const git = "git+https://github.com/example/a?rev=1#1";
  const gitPkg = (v) => ({ name: "a", version: v, source: git, checksum: undefined });
  const result = validateLockfileUpdate(
    renderLock([APP, gitPkg("1.2.0")]),
    renderLock([APP, gitPkg("1.2.5")]),
  );
  assert.ok(!result.ok);
  assert.match(result.errors.join("\n"), /source is not crates\.io/);
  // A same-version source swap no longer pairs (source identity is part
  // of the pairing key), so it surfaces as a non-crates.io arrival — still
  // refused, under the arrival rule.
  const swapped = validateLockfileUpdate(
    renderLock([APP, reg({ name: "a", version: "1.2.0" })]),
    renderLock([APP, gitPkg("1.2.0")]),
  );
  assert.ok(!swapped.ok);
  assert.match(swapped.errors.join("\n"), /arrived from a source that is not crates\.io/);
});

test("the same crate at compatible versions from two git sources is a valid graph", () => {
  const g = (repo, frag) => `git+https://github.com/${repo}/dupe?rev=x#${frag}`;
  const at = (a) =>
    renderLock([
      { name: "app", version: "0.0.0", deps: [`dupe 1.2.3 (${g("x", "111")})`, `dupe 1.2.3 (${g("y", "222")})`, "a"] },
      { name: "dupe", version: "1.2.3", source: g("x", "111") },
      { name: "dupe", version: "1.2.3", source: g("y", "222") },
      reg({ name: "a", version: a }),
    ]);
  const result = validateLockfileUpdate(at("1.2.0"), at("1.2.5"));
  assert.deepEqual(result.errors, []);
  assert.deepEqual(result.changes.map((c) => c.name), ["a"]);
});

test("soundness: unresolvable, ambiguous, and orphaned packages are refused", () => {
  const dangling = parseLockfile(renderLock([{ name: "app", version: "0.0.0", deps: ["ghost"] }]));
  assert.match(soundnessFailures(dangling, "t").join("\n"), /resolves to 0 packages/);
  const ambiguous = parseLockfile(
    renderLock([
      { name: "app", version: "0.0.0", deps: ["syn"] },
      reg({ name: "syn", version: "2.0.119" }),
      reg({ name: "syn", version: "3.0.2" }),
    ]),
  );
  assert.match(soundnessFailures(ambiguous, "t").join("\n"), /resolves to 2 packages/);
  const orphaned = parseLockfile(
    renderLock([{ name: "app", version: "0.0.0" }, reg({ name: "stray", version: "1.0.0" })]),
  );
  assert.match(soundnessFailures(orphaned, "t").join("\n"), /not reachable/);
});

test("an unchanged package gaining a declared-looking edge is collected, not decided", () => {
  const result = validateLockfileUpdate(
    renderLock([
      { name: "app", version: "0.0.0", deps: ["a", "b"] },
      reg({ name: "a", version: "1.2.0" }),
      reg({ name: "b", version: "2.0.0" }),
    ]),
    renderLock([
      { name: "app", version: "0.0.0", deps: ["a", "b"] },
      reg({ name: "a", version: "1.2.5" }),
      // b held still but now records an edge — feature unification, or a graft.
      reg({ name: "b", version: "2.0.0", deps: ["a"] }),
    ]),
  );
  assert.deepEqual(result.errors, []);
  assert.deepEqual(result.depChanged, [{ name: "b", version: "2.0.0", added: ["a"], removed: [] }]);
});

test("an identical lockfile is nothing to publish", () => {
  const text = renderLock([APP, reg({ name: "a", version: "1.2.0" })]);
  const result = validateLockfileUpdate(text, text);
  assert.ok(!result.ok);
  assert.match(result.errors.join("\n"), /nothing to publish/);
});

// ---------------------------------------------------------------------------
// Upstream verification.
// ---------------------------------------------------------------------------

const NOW = new Date("2026-08-18T12:00:00Z");
const OLD_DATE = "2026-08-01T00:00:00Z";
const FRESH_DATE = "2026-08-17T00:00:00Z";

// crates: { name: { versions: [{vers, cksum?, yanked?, deps?}], dates } }
const upstream = (crates) => {
  const requests = [];
  const fetcher = async (url) => {
    requests.push(url);
    const api = /crates\.io\/api\/v1\/crates\/([^/]+)\/([^/]+)$/.exec(url);
    if (api) {
      const date = crates[api[1]]?.dates?.[api[2]];
      if (!date) return { ok: false, status: 404, json: async () => ({}) };
      return { ok: true, json: async () => ({ version: { created_at: date } }) };
    }
    const name = url.slice(url.lastIndexOf("/") + 1);
    const crate = crates[name];
    if (!crate) return { ok: false, status: 404, text: async () => "" };
    return {
      ok: true,
      text: async () =>
        crate.versions
          .map((v) =>
            JSON.stringify({
              name,
              vers: v.vers,
              cksum: v.cksum ?? `c-${name}-${v.vers}`,
              yanked: v.yanked ?? false,
              deps: v.deps ?? [],
            }),
          )
          .join("\n"),
    };
  };
  return { fetcher, requests };
};

const CHANGE = { name: "a", from: "1.2.0", to: "1.2.5", checksum: "c-a-1.2.5" };
const A_AT_125 = renderLock([APP, reg({ name: "a", version: "1.2.5" })]);
const settings = (fetcher, extra = {}) => ({ fetcher, cooldownDays: 5, now: NOW, ...extra });

test("verifyUpstream passes a listed, un-yanked, checksum-matching, aged release", async () => {
  const newText = renderLock([
    APP,
    reg({ name: "a", version: "1.2.5", deps: ["memchr"] }),
    reg({ name: "memchr", version: "2.7.4" }),
  ]);
  const { fetcher, requests } = upstream({
    a: {
      versions: [{ vers: "1.2.0" }, { vers: "1.2.5", deps: [{ name: "memchr", req: "^2" }] }],
      dates: { "1.2.5": OLD_DATE },
    },
    memchr: { versions: [{ vers: "2.7.4" }], dates: {} },
  });
  const errors = await verifyUpstream(newText, { changes: [CHANGE], added: [] }, settings(fetcher));
  assert.deepEqual(errors, []);
  // The date was really consulted — the cooldown path ran.
  assert.ok(requests.some((u) => u.includes("/crates/a/1.2.5")));
});

test("verifyUpstream refuses what the registry does not vouch for", async () => {
  const cases = [
    [{ a: { versions: [{ vers: "1.2.0" }], dates: {} } }, /does not list version 1\.2\.5/],
    [{ a: { versions: [{ vers: "1.2.5", yanked: true }], dates: {} } }, /yanked upstream/],
    [
      { a: { versions: [{ vers: "1.2.5", cksum: "different" }], dates: { "1.2.5": OLD_DATE } } },
      /checksum does not match the registry/,
    ],
    [
      { a: { versions: [{ vers: "1.2.5" }], dates: { "1.2.5": FRESH_DATE } } },
      /inside the 5-day cooldown/,
    ],
    [{ a: { versions: [{ vers: "1.2.5" }], dates: {} } }, /no publish date/],
  ];
  for (const [crates, message] of cases) {
    const { fetcher } = upstream(crates);
    const errors = await verifyUpstream(A_AT_125, { changes: [CHANGE], added: [] }, settings(fetcher));
    assert.equal(errors.length, 1, String(message));
    assert.match(errors[0], message);
  }
});

test("the graph pass refuses a dependency edge the version does not declare", async () => {
  const newText = renderLock([
    APP,
    reg({ name: "a", version: "1.2.5", deps: ["grafted"] }),
    reg({ name: "grafted", version: "1.0.0" }),
  ]);
  const { fetcher } = upstream({
    // memchr is optional here so the graft is this fixture's ONE finding —
    // the mandatory-edge rule has its own test below.
    a: {
      versions: [{ vers: "1.2.5", deps: [{ name: "memchr", req: "^2", optional: true }] }],
      dates: { "1.2.5": OLD_DATE },
    },
    grafted: { versions: [{ vers: "1.0.0" }], dates: {} },
  });
  const errors = await verifyUpstream(newText, { changes: [CHANGE], added: [] }, settings(fetcher));
  assert.equal(errors.length, 1);
  assert.match(errors[0], /dependency on grafted/);
});

test("the graph pass refuses a dropped mandatory edge, and only that", async () => {
  // A forged artifact records the updated package with NO dependencies,
  // deleting a required subtree: soundness and every subset check stay
  // green, so the required set has to be re-derived from the index. The
  // optional and dev declarations are legitimately absent.
  const newText = A_AT_125;
  const { fetcher } = upstream({
    a: {
      versions: [
        {
          vers: "1.2.5",
          deps: [
            { name: "memchr", req: "^2" },
            { name: "extras", req: "^1", optional: true },
            { name: "harness", req: "^3", kind: "dev" },
          ],
        },
      ],
      dates: { "1.2.5": OLD_DATE },
    },
  });
  const errors = await verifyUpstream(newText, { changes: [CHANGE], added: [] }, settings(fetcher));
  assert.equal(errors.length, 1);
  assert.match(errors[0], /omits its mandatory dependency memchr/);
});

test("the graph pass refuses a resolution the declared requirement never allowed", async () => {
  // b's old major survives beside a new one, and the artifact points an
  // UNCHANGED package's edge at the copy its `^1` cannot mean — the tamper
  // the trust model says this runner must catch on its own.
  const newText = renderLock([
    { name: "app", version: "0.0.0", deps: ["p", "q"] },
    reg({ name: "p", version: "3.0.0", deps: ["b 2.0.1"] }),
    reg({ name: "q", version: "1.0.0", deps: ["b 1.4.0"] }),
    reg({ name: "b", version: "1.4.0" }),
    reg({ name: "b", version: "2.0.1" }),
  ]);
  const { fetcher } = upstream({
    p: { versions: [{ vers: "3.0.0", deps: [{ name: "b", req: "^1" }] }], dates: {} },
    q: { versions: [{ vers: "1.0.0", deps: [{ name: "b", req: "^1" }] }], dates: {} },
    b: { versions: [{ vers: "1.4.0" }, { vers: "2.0.1" }], dates: {} },
  });
  const errors = await verifyUpstream(newText, { changes: [], added: [] }, settings(fetcher));
  assert.equal(errors.length, 1);
  assert.match(errors[0], /p 3\.0\.0: resolves b to 2\.0\.1, which satisfies none/);
});

test("the graph pass fails closed on a requirement it cannot understand", async () => {
  const newText = renderLock([APP, reg({ name: "a", version: "1.2.5", deps: ["m"] }), reg({ name: "m", version: "2.7.4" })]);
  const { fetcher } = upstream({
    a: { versions: [{ vers: "1.2.5", deps: [{ name: "m", req: "certainly not semver" }] }], dates: { "1.2.5": OLD_DATE } },
    m: { versions: [{ vers: "2.7.4" }], dates: {} },
  });
  const errors = await verifyUpstream(newText, { changes: [CHANGE], added: [] }, settings(fetcher));
  assert.equal(errors.length, 1);
  assert.match(errors[0], /could not be understood/);
});

test("the graph pass accepts a renamed dependency by its real crate name", async () => {
  const newText = renderLock([
    APP,
    reg({ name: "a", version: "1.2.5", deps: ["real-crate"] }),
    reg({ name: "real-crate", version: "1.1.0" }),
  ]);
  const { fetcher } = upstream({
    a: {
      versions: [{ vers: "1.2.5", deps: [{ name: "alias", package: "real-crate", req: "^1" }] }],
      dates: { "1.2.5": OLD_DATE },
    },
    "real-crate": { versions: [{ vers: "1.1.0" }], dates: {} },
  });
  const errors = await verifyUpstream(newText, { changes: [CHANGE], added: [] }, settings(fetcher));
  assert.deepEqual(errors, []);
});

test("a kind-split dependency is admitted when any declared requirement allows it", async () => {
  // The same crate declared twice — a normal dep at ^2 and a dev dep at
  // ^1 — resolves two copies; each edge is legitimate under one of them.
  const newText = renderLock([
    APP,
    reg({ name: "a", version: "1.2.5", deps: ["m 1.9.0", "m 2.7.4"] }),
    reg({ name: "m", version: "1.9.0" }),
    reg({ name: "m", version: "2.7.4" }),
  ]);
  const { fetcher } = upstream({
    a: {
      versions: [
        { vers: "1.2.5", deps: [{ name: "m", req: "^2" }, { name: "m", req: "^1", kind: "dev" }] },
      ],
      dates: { "1.2.5": OLD_DATE },
    },
    m: { versions: [{ vers: "1.9.0" }, { vers: "2.7.4" }], dates: {} },
  });
  const errors = await verifyUpstream(newText, { changes: [CHANGE], added: [] }, settings(fetcher));
  assert.deepEqual(errors, []);
});

test("a zero cooldown still requires existence and checksum, but no date", async () => {
  const { fetcher, requests } = upstream({ a: { versions: [{ vers: "1.2.5" }], dates: {} } });
  const errors = await verifyUpstream(
    A_AT_125,
    { changes: [CHANGE], added: [] },
    settings(fetcher, { cooldownDays: 0 }),
  );
  assert.deepEqual(errors, []);
  assert.ok(!requests.some((u) => u.includes("/api/")));
});

test("verifyUpstream checks additions like changes", async () => {
  const newText = renderLock([
    { name: "app", version: "0.0.0", deps: ["fresh"] },
    reg({ name: "fresh", version: "0.7.2" }),
  ]);
  const { fetcher } = upstream({ fresh: { versions: [{ vers: "0.7.2" }], dates: { "0.7.2": FRESH_DATE } } });
  const errors = await verifyUpstream(
    newText,
    { changes: [], added: [{ name: "fresh", version: "0.7.2", checksum: "c-fresh-0.7.2" }] },
    settings(fetcher),
  );
  assert.equal(errors.length, 1);
  assert.match(errors[0], /fresh 0\.7\.2: published .* inside the 5-day cooldown/);
});
