// Runs the real engine against fixture lockfiles, a stubbed cargo, and a
// stubbed registry. The suite's failure mode is a false pass — a fixture
// that stops matching the code path it names still goes green — so where a
// case depends on the stub having served or refused something, the test
// asserts it did.

import { test } from "node:test";
import assert from "node:assert/strict";
import {
  API_URL,
  CRATES_IO_SOURCE,
  INDEX_URL,
  compareSemver,
  compatKeyOf,
  diffLockfiles,
  directDepNames,
  fetchCrateIndex,
  fetchVersionDate,
  findPinback,
  httpsFetcher,
  indexPathFor,
  isStable,
  parseDepRef,
  parseLockfile,
  parseSemver,
  reportMarkdown,
  reqMatches,
  resolveDepRef,
  updateLockfile,
  workspaceMembers,
} from "./update-lockfile.mjs";

// ---------------------------------------------------------------------------
// Fixture builders: a lockfile renderer matching Cargo's serializer shape,
// a registry stub serving the sparse index and the crates.io API, and a
// cargo stub that mutates the in-memory lockfile the way the real one
// mutates the file.
// ---------------------------------------------------------------------------

const renderLock = (packages, { version = 4, extra = "" } = {}) => {
  let out =
    "# This file is automatically @generated by Cargo.\n" +
    "# It is not intended for manual editing.\n" +
    `version = ${version}\n`;
  for (const p of packages) {
    out += `\n[[package]]\nname = "${p.name}"\nversion = "${p.version}"\n`;
    if (p.source !== undefined && p.source !== null) out += `source = "${p.source}"\n`;
    if (p.checksum !== undefined) out += `checksum = "${p.checksum}"\n`;
    else if (p.source !== undefined && p.source !== null) out += `checksum = "c-${p.name}-${p.version}"\n`;
    if (p.deps !== undefined && p.deps.length > 0) {
      out += "dependencies = [\n";
      for (const d of p.deps) out += ` "${d}",\n`;
      out += "]\n";
    }
  }
  return out + extra;
};

const reg = (p) => ({ source: CRATES_IO_SOURCE, ...p });

// crates: { name: { versions: [{vers, yanked?, cksum?, deps?}], dates: { vers: iso } } }
const makeFetcher = (crates) => {
  const requests = [];
  const fetcher = async (url) => {
    requests.push(url);
    if (url.startsWith(INDEX_URL + "/")) {
      const name = url.slice(url.lastIndexOf("/") + 1);
      const crate = crates[name];
      if (!crate) return { ok: false, status: 404, text: async () => "" };
      const body = crate.versions
        .map((v) =>
          JSON.stringify({
            name,
            vers: v.vers,
            cksum: v.cksum ?? `c-${name}-${v.vers}`,
            yanked: v.yanked ?? false,
            deps: v.deps ?? [],
          }),
        )
        .join("\n");
      return { ok: true, status: 200, text: async () => body };
    }
    const api = new RegExp(`^${API_URL}/crates/([^/]+)/([^/]+)$`).exec(url);
    if (api) {
      const crate = crates[decodeURIComponent(api[1])];
      const date = crate?.dates?.[decodeURIComponent(api[2])];
      if (!date) return { ok: false, status: 404, json: async () => ({}) };
      return { ok: true, status: 200, json: async () => ({ version: { created_at: date } }) };
    }
    throw new Error(`unexpected URL: ${url}`);
  };
  return { fetcher, requests };
};

// A cargo whose `update` swaps in a prepared resolution and whose
// `--precise` rewrites one package's version in place (checksum too, as the
// real one does). `refuse` lets a test model the resolver rejecting a pin;
// `onPrecise` lets one model a pin that reshapes the graph.
const makeCargo = (state, { updated, refuse, onPrecise } = {}) => {
  const calls = [];
  const runCargo = (args) => {
    calls.push(args.join(" "));
    if (args.length === 1 && args[0] === "update") {
      state.text = updated;
      return { ok: true, output: "" };
    }
    if (args[0] === "update" && args[2] === "--precise") {
      const spec = args[1];
      const bare = spec.includes("#") ? spec.slice(spec.indexOf("#") + 1) : spec;
      const [name, at] = bare.split("@");
      const to = args[3];
      if (refuse && refuse(name, at, to)) {
        return { ok: false, output: `error: failed to select a version for ${name}` };
      }
      if (onPrecise) {
        state.text = onPrecise(name, at, to, state.text);
        return { ok: true, output: "" };
      }
      const lock = parseLockfile(state.text);
      const pkg = lock.packages.find((p) => p.name === name && p.version === at);
      if (!pkg) return { ok: false, output: `error: package ID specification ${args[1]} did not match` };
      state.text = state.text
        .replace(`name = "${name}"\nversion = "${at}"`, `name = "${name}"\nversion = "${to}"`)
        .replace(`checksum = "c-${name}-${at}"`, `checksum = "c-${name}-${to}"`);
      return { ok: true, output: "" };
    }
    throw new Error(`unexpected cargo invocation: ${args.join(" ")}`);
  };
  return { runCargo, calls };
};

const NOW = new Date("2026-08-18T12:00:00Z");
const OLD_DATE = "2026-08-01T00:00:00Z"; // outside a 5-day cooldown
const FRESH_DATE = "2026-08-17T00:00:00Z"; // inside it

const runUpdate = (state, cargoOpts, crates, opts = {}) => {
  const cargo = makeCargo(state, cargoOpts);
  const net = makeFetcher(crates);
  const result = updateLockfile({
    readLockfile: () => state.text,
    runCargo: cargo.runCargo,
    fetcher: net.fetcher,
    now: NOW,
    cooldownDays: 5,
    ...opts,
  });
  return { result, cargo, net };
};

// ---------------------------------------------------------------------------
// Parser.
// ---------------------------------------------------------------------------

test("parseLockfile reads packages, workspace members, and raw extra sections", () => {
  const text = renderLock(
    [
      reg({ name: "libc", version: "0.2.186", deps: [] }),
      { name: "app", version: "0.0.0", deps: ["libc", "syn 2.0.119"] },
    ],
    { extra: '\n[[patch.unused]]\nname = "quux"\nversion = "1.0.0"\n' },
  );
  const lock = parseLockfile(text);
  assert.deepEqual(lock.errors, []);
  assert.equal(lock.version, 4);
  assert.equal(lock.packages.length, 2);
  assert.equal(lock.packages[0].source, CRATES_IO_SOURCE);
  assert.equal(lock.packages[0].checksum, "c-libc-0.2.186");
  assert.equal(lock.packages[1].source, null);
  assert.deepEqual(lock.packages[1].dependencies, ["libc", "syn 2.0.119"]);
  assert.equal(lock.others.length, 1);
  assert.match(lock.others[0].header, /patch\.unused/);
  assert.match(lock.others[0].raw.join("\n"), /quux/);
  assert.deepEqual(workspaceMembers(lock).map((p) => p.name), ["app"]);
});

test("parseLockfile refuses fields and shapes Cargo does not emit", () => {
  for (const [mutation, message] of [
    ["replace = \"other 1.0.0\"", /unrecognized package field/],
    ["name = \"twice\"", /duplicate name/],
  ]) {
    const text = renderLock([reg({ name: "a", version: "1.0.0" })]).replace(
      'checksum = "c-a-1.0.0"',
      `checksum = "c-a-1.0.0"\n${mutation}`,
    );
    const lock = parseLockfile(text);
    assert.equal(lock.errors.length, 1, mutation);
    assert.match(lock.errors[0], message);
  }
  assert.match(
    parseLockfile('[[package]]\nname = "a"\nversion = "1.0.0"\n').errors.join("\n"),
    /no `version = N` line/,
  );
  assert.match(
    parseLockfile(renderLock([]) + '\n[[package]]\nname = "a"\nversion = "1.0.0"\ndependencies = [\n "b",\n').errors.join("\n"),
    /unterminated dependencies/,
  );
});

test("dependency references parse and resolve in all three spellings", () => {
  assert.deepEqual(parseDepRef("memchr"), { name: "memchr", version: null, source: null });
  assert.deepEqual(parseDepRef("syn 2.0.119"), { name: "syn", version: "2.0.119", source: null });
  assert.deepEqual(parseDepRef(`foo 1.0.0 (${CRATES_IO_SOURCE})`), {
    name: "foo",
    version: "1.0.0",
    source: CRATES_IO_SOURCE,
  });
  const packages = [
    reg({ name: "syn", version: "2.0.119" }),
    reg({ name: "syn", version: "3.0.2" }),
    reg({ name: "memchr", version: "2.7.4" }),
  ];
  assert.equal(resolveDepRef(packages, "memchr").length, 1);
  assert.equal(resolveDepRef(packages, "syn").length, 2); // ambiguous — caller's problem to refuse
  assert.equal(resolveDepRef(packages, "syn 2.0.119")[0].version, "2.0.119");
});

// ---------------------------------------------------------------------------
// Semver.
// ---------------------------------------------------------------------------

test("semver parsing, ordering, and stability", () => {
  assert.deepEqual(parseSemver("1.2.3"), { major: 1, minor: 2, patch: 3, prerelease: null });
  assert.equal(parseSemver("1.2"), null);
  assert.equal(parseSemver("01.2.3"), null);
  assert.ok(compareSemver("1.2.10", "1.2.9") > 0);
  assert.ok(compareSemver("1.0.0-alpha", "1.0.0") < 0);
  assert.ok(compareSemver("1.0.0-alpha.1", "1.0.0-alpha") > 0);
  assert.ok(compareSemver("1.0.0-2", "1.0.0-11") < 0); // numeric identifiers compare numerically
  assert.ok(compareSemver("1.0.0-alpha", "1.0.0-1") > 0); // numeric below alphanumeric
  assert.equal(compareSemver("1.0.0+a", "1.0.0+b"), 0); // build metadata ignored
  assert.ok(isStable("1.2.3"));
  assert.ok(isStable("1.2.3+meta"));
  assert.ok(!isStable("1.2.3-rc.1"));
  assert.ok(!isStable("not-a-version"));
});

test("reqMatches transcribes the semver crate's comparator semantics", () => {
  const table = [
    // caret, bare-as-caret, and the 0.x ladder
    ["^1.2.3", "1.2.4", true], ["^1.2.3", "1.3.0", true], ["^1.2.3", "2.0.0", false],
    ["^1.2.3", "1.2.2", false], ["1.2.3", "1.2.4", true],
    ["^0.2.3", "0.2.9", true], ["^0.2.3", "0.3.0", false],
    ["^0.0.3", "0.0.3", true], ["^0.0.3", "0.0.4", false],
    ["^0", "0.9.9", true], ["^0", "1.0.0", false],
    ["^0.0", "0.0.9", true], ["^0.0", "0.1.0", false],
    // tilde
    ["~1.2.3", "1.2.9", true], ["~1.2.3", "1.3.0", false],
    ["~1.2", "1.2.0", true], ["~1.2", "1.3.0", false],
    ["~1", "1.9.0", true], ["~1", "2.0.0", false],
    // exact, full and partial
    ["=1.2.3", "1.2.3", true], ["=1.2.3", "1.2.4", false],
    ["=1.2", "1.2.9", true], ["=1.2", "1.3.0", false],
    // ordered comparators, partials per the crate's equivalences
    [">=1.2, <1.5", "1.4.0", true], [">=1.2, <1.5", "1.5.0", false],
    [">1.2", "1.3.0", true], [">1.2", "1.2.9", false],
    ["<=1.2", "1.2.9", true], ["<=1.2", "1.3.0", false],
    ["<1", "0.9.0", true], ["<1", "1.0.0", false],
    // wildcards
    ["*", "1.0.0", true], ["1.*", "1.5.0", true], ["1.*", "2.0.0", false],
    // the prerelease gate: same triple plus a prerelease on the comparator
    ["*", "1.0.0-rc.1", false], [">=1.0.0", "1.0.1-rc.1", false],
    ["=2.0.0-rc.1", "2.0.0-rc.1", true], [">=1.0.0-alpha", "1.0.0-beta", true],
    // admission is per REQUIREMENT: one same-triple prerelease comparator
    // admits the version for every other comparator's ordinary ordering
    [">=1.0.0-alpha, <2.0.0", "1.0.0-beta", true], ["<2.0.0", "1.0.0-beta", false],
    // refusals, never passes
    ["bogus", "1.0.0", null], [">=*", "1.0.0", null], ["~1.2-beta", "1.2.0", null],
    ["", "1.0.0", null], ["^1.0.0", "not-a-version", null],
  ];
  for (const [req, version, expected] of table) {
    assert.equal(reqMatches(req, version), expected, `${JSON.stringify(req)} vs ${version}`);
  }
});

test("compatKeyOf mirrors Cargo's caret rule", () => {
  assert.equal(compatKeyOf("1.2.3"), "1");
  assert.equal(compatKeyOf("0.2.9"), "0.2");
  assert.equal(compatKeyOf("0.0.3"), "0.0.3");
  assert.equal(compatKeyOf("2.0.0-rc.1"), "2");
  assert.equal(compatKeyOf("garbage"), null);
});

// ---------------------------------------------------------------------------
// Diff.
// ---------------------------------------------------------------------------

test("diffLockfiles pairs compat groups and separates arrivals from departures", () => {
  const before = parseLockfile(
    renderLock([
      reg({ name: "a", version: "1.2.0" }),
      reg({ name: "syn", version: "2.0.119" }),
      reg({ name: "gone", version: "0.3.1" }),
    ]),
  );
  const after = parseLockfile(
    renderLock([
      reg({ name: "a", version: "1.3.0" }),
      reg({ name: "syn", version: "2.0.119" }),
      reg({ name: "syn", version: "3.0.2" }),
      reg({ name: "fresh", version: "0.1.0" }),
    ]),
  );
  const diff = diffLockfiles(before, after);
  assert.deepEqual(diff.errors, []);
  assert.deepEqual(diff.changed.map((c) => `${c.name} ${c.from}->${c.to}`), ["a 1.2.0->1.3.0"]);
  assert.deepEqual(diff.added.map((p) => `${p.name} ${p.version}`).sort(), ["fresh 0.1.0", "syn 3.0.2"]);
  assert.deepEqual(diff.removed.map((p) => `${p.name} ${p.version}`), ["gone 0.3.1"]);
  assert.equal(diff.unchanged.length, 1);
});

test("diffLockfiles refuses two semver-compatible versions of one crate", () => {
  const twice = parseLockfile(
    renderLock([reg({ name: "a", version: "1.2.0" }), reg({ name: "a", version: "1.3.0" })]),
  );
  const diff = diffLockfiles(twice, twice);
  assert.ok(diff.errors.length >= 1);
  assert.match(diff.errors[0], /two semver-compatible versions/);
});

test("directDepNames spans members and skips member-to-member edges", () => {
  const lock = parseLockfile(
    renderLock([
      { name: "app", version: "0.0.0", deps: ["core", "libc"] },
      { name: "core", version: "0.0.0", deps: ["regex"] },
      reg({ name: "libc", version: "0.2.186" }),
      reg({ name: "regex", version: "1.11.3", deps: [] }),
    ]),
  );
  assert.deepEqual([...directDepNames(lock)].sort(), ["libc", "regex"]);
});

// ---------------------------------------------------------------------------
// Registry metadata.
// ---------------------------------------------------------------------------

test("indexPathFor follows the sparse index scheme, lowercased", () => {
  assert.equal(indexPathFor("a"), "1/a");
  assert.equal(indexPathFor("ab"), "2/ab");
  assert.equal(indexPathFor("syn"), "3/s/syn");
  assert.equal(indexPathFor("serde"), "se/rd/serde");
  assert.equal(indexPathFor("Inflector"), "in/fl/inflector");
});

test("fetchCrateIndex parses records and fails closed on the shapes it cannot", async () => {
  const { fetcher } = makeFetcher({ serde: { versions: [{ vers: "1.0.0" }, { vers: "1.0.1", yanked: true }] } });
  const good = await fetchCrateIndex("serde", fetcher);
  assert.deepEqual(good.errors, []);
  assert.deepEqual(good.versions.map((v) => `${v.vers}${v.yanked ? " yanked" : ""}`), ["1.0.0", "1.0.1 yanked"]);
  const missing = await fetchCrateIndex("no-such-crate", fetcher);
  assert.equal(missing.versions.length, 0);
  assert.match(missing.errors[0], /HTTP 404/);
  const garbled = await fetchCrateIndex("x", async () => ({ ok: true, status: 200, text: async () => "not json" }));
  assert.match(garbled.errors[0], /unparseable index line/);
});

test("fetchVersionDate reads created_at and returns null on any failure", async () => {
  const { fetcher } = makeFetcher({ serde: { versions: [], dates: { "1.0.0": OLD_DATE } } });
  assert.equal((await fetchVersionDate("serde", "1.0.0", fetcher)).getTime(), new Date(OLD_DATE).getTime());
  assert.equal(await fetchVersionDate("serde", "9.9.9", fetcher), null);
  assert.equal(await fetchVersionDate("serde", "1.0.0", async () => { throw new Error("down"); }), null);
});

// ---------------------------------------------------------------------------
// The pin-back walk.
// ---------------------------------------------------------------------------

const walkDeps = (crates) => {
  const { fetcher } = makeFetcher(crates);
  return {
    cooldownDays: 5,
    now: NOW,
    versionDate: (name, version) => fetchVersionDate(name, version, fetcher),
  };
};

test("findPinback takes the newest eligible candidate below the chosen one", async () => {
  const crates = {
    a: {
      versions: [
        { vers: "1.2.0" }, { vers: "1.2.1" }, { vers: "1.2.2", yanked: true },
        { vers: "1.2.3-rc.1" }, { vers: "1.2.4" }, { vers: "1.2.5" }, { vers: "2.0.0" },
      ],
      dates: { "1.2.1": OLD_DATE, "1.2.4": OLD_DATE, "1.2.5": FRESH_DATE },
    },
  };
  const { candidate, reasons } = await findPinback(
    "a", "1.2.5", "1.2.0",
    { versions: crates.a.versions },
    walkDeps(crates),
  );
  // 1.2.4 wins: 1.2.5 is the vacated version, 2.0.0 is out of the group,
  // the rc and the yank never qualify — and the reasons say nothing,
  // because nothing eligible was passed over.
  assert.equal(candidate, "1.2.4");
  assert.deepEqual(reasons, []);
});

test("findPinback respects the floor, defers cooling candidates, and caps missing dates", async () => {
  const crates = {
    a: {
      versions: [{ vers: "1.2.1" }, { vers: "1.2.2" }, { vers: "1.2.3" }, { vers: "1.2.4" }],
      dates: { "1.2.4": FRESH_DATE, "1.2.1": OLD_DATE },
    },
  };
  // Floor 1.2.2: only 1.2.4 (cooling) and 1.2.3 (dateless) sit strictly
  // between the floor and the vacated 1.2.5, so nothing qualifies — the
  // floor itself is excluded because the caller's own fallback covers it.
  const walk = walkDeps(crates);
  const held = await findPinback("a", "1.2.5", "1.2.2", { versions: crates.a.versions }, walk);
  assert.equal(held.candidate, null);
  assert.equal(held.reasons.length, 2);
  assert.match(held.reasons[0], /inside the 5-day cooldown/);
  assert.match(held.reasons[1], /no publish date/);
  // Floor lifted: the walk continues past the dateless pair to 1.2.1.
  const found = await findPinback("a", "1.2.5", null, { versions: crates.a.versions }, walk);
  assert.equal(found.candidate, "1.2.1");
});

// ---------------------------------------------------------------------------
// The whole update.
// ---------------------------------------------------------------------------

const APP = { name: "app", version: "0.0.0", deps: ["a"] };

test("a plain in-range bump outside the cooldown goes straight through", async () => {
  const state = { text: renderLock([APP, reg({ name: "a", version: "1.2.0" })]) };
  const { result, cargo, net } = runUpdate(
    state,
    { updated: renderLock([APP, reg({ name: "a", version: "1.2.5" })]) },
    { a: { versions: [{ vers: "1.2.0" }, { vers: "1.2.5" }], dates: { "1.2.5": OLD_DATE } } },
  );
  const report = await result;
  assert.deepEqual(report.blocking, []);
  assert.deepEqual(report.changes, [{ name: "a", from: "1.2.0", to: "1.2.5", direct: true }]);
  assert.deepEqual(cargo.calls, ["update"]);
  // The date was actually asked, not assumed: the cooldown path ran.
  assert.ok(net.requests.some((u) => u.includes("/crates/a/1.2.5")));
});

test("a bump inside the cooldown is pinned back to the newest eligible release", async () => {
  const state = { text: renderLock([APP, reg({ name: "a", version: "1.2.0" })]) };
  const { result, cargo } = runUpdate(
    state,
    { updated: renderLock([APP, reg({ name: "a", version: "1.2.5" })]) },
    {
      a: {
        versions: [{ vers: "1.2.0" }, { vers: "1.2.4" }, { vers: "1.2.5" }],
        dates: { "1.2.5": FRESH_DATE, "1.2.4": OLD_DATE },
      },
    },
  );
  const report = await result;
  assert.deepEqual(report.blocking, []);
  assert.deepEqual(cargo.calls, ["update", "update a@1.2.5 --precise 1.2.4"]);
  assert.deepEqual(report.changes, [{ name: "a", from: "1.2.0", to: "1.2.4", direct: true }]);
  assert.equal(report.cooldown.length, 1);
  assert.equal(report.cooldown[0].to, "1.2.4");
  assert.match(report.cooldown[0].reasons[0], /inside the 5-day cooldown/);
});

test("with no eligible release in between, a changed package stays where it started", async () => {
  const state = { text: renderLock([APP, reg({ name: "a", version: "1.2.0" })]) };
  const { result, cargo } = runUpdate(
    state,
    { updated: renderLock([APP, reg({ name: "a", version: "1.2.5" })]) },
    {
      a: {
        versions: [{ vers: "1.2.0" }, { vers: "1.2.5" }],
        dates: { "1.2.5": FRESH_DATE, "1.2.0": OLD_DATE },
      },
    },
  );
  const report = await result;
  assert.deepEqual(report.blocking, []);
  assert.deepEqual(cargo.calls, ["update", "update a@1.2.5 --precise 1.2.0"]);
  assert.deepEqual(report.changes, []);
  assert.equal(report.cooldown[0].to, null);
});

test("a new arrival with nothing eligible below it blocks the batch", async () => {
  const withDep = { ...APP, deps: ["a"] };
  const state = { text: renderLock([withDep, reg({ name: "a", version: "1.2.0" })]) };
  const { result } = runUpdate(
    state,
    {
      updated: renderLock([
        withDep,
        reg({ name: "a", version: "1.2.5", deps: ["brand-new"] }),
        reg({ name: "brand-new", version: "0.1.0" }),
      ]),
    },
    {
      a: { versions: [{ vers: "1.2.0" }, { vers: "1.2.5" }], dates: { "1.2.5": OLD_DATE } },
      "brand-new": { versions: [{ vers: "0.1.0" }], dates: { "0.1.0": FRESH_DATE } },
    },
  );
  const report = await result;
  assert.equal(report.blocking.length, 1);
  assert.match(report.blocking[0], /brand-new/);
  assert.match(report.blocking[0], /no older release in its compatibility range/);
});

test("a transitive major is unwound by pinning the dependent that dragged it", async () => {
  const before = renderLock([
    APP,
    reg({ name: "a", version: "1.2.0", deps: ["b"] }),
    reg({ name: "b", version: "1.4.0" }),
  ]);
  const after = renderLock([
    APP,
    reg({ name: "a", version: "1.3.0", deps: ["b"] }),
    reg({ name: "b", version: "2.0.1" }),
  ]);
  const state = { text: before };
  const { result, cargo } = runUpdate(
    state,
    { updated: after, onPrecise: () => before }, // pinning a back restores b too
    {
      a: { versions: [{ vers: "1.2.0" }, { vers: "1.3.0" }], dates: { "1.3.0": OLD_DATE } },
      b: { versions: [{ vers: "1.4.0" }, { vers: "2.0.1" }], dates: { "2.0.1": OLD_DATE } },
    },
  );
  const report = await result;
  assert.deepEqual(report.blocking, []);
  assert.deepEqual(cargo.calls, ["update", "update a@1.3.0 --precise 1.2.0"]);
  assert.deepEqual(report.changes, []);
  assert.equal(report.crossings.length, 1);
  assert.equal(report.crossings[0].name, "a");
  assert.equal(report.crossings[0].dragged.name, "b");
  assert.match(reportMarkdown(report), /would drag a transitive major/);
});

test("a crossed edge on an unchanged package blocks instead of guessing", async () => {
  // b crosses majors but its only dependent is the workspace member, which
  // never changes — nothing to pin, so the batch must stop.
  const state = {
    text: renderLock([{ name: "app", version: "0.0.0", deps: ["b"] }, reg({ name: "b", version: "1.4.0" })]),
  };
  const { result } = runUpdate(
    state,
    {
      updated: renderLock([
        { name: "app", version: "0.0.0", deps: ["b"] },
        reg({ name: "b", version: "2.0.1" }),
      ]),
    },
    { b: { versions: [{ vers: "1.4.0" }, { vers: "2.0.1" }], dates: { "2.0.1": OLD_DATE } } },
  );
  const report = await result;
  assert.equal(report.blocking.length, 1);
  assert.match(report.blocking[0], /did not itself change/);
});

test("a crossing hidden behind a surviving old major is still unwound", async () => {
  // Two dependents share b 1.x; a's in-range bump moves ITS edge to a new
  // b 2.x while the other dependent keeps 1.x alive — no compat group is
  // lost, so only a per-edge comparison sees the move. a is pinned back.
  const before = renderLock([
    { name: "app", version: "0.0.0", deps: ["a", "keeper"] },
    reg({ name: "a", version: "1.2.0", deps: ["b 1.4.0"] }),
    reg({ name: "keeper", version: "3.1.0", deps: ["b 1.4.0"] }),
    reg({ name: "b", version: "1.4.0" }),
  ]);
  const after = renderLock([
    { name: "app", version: "0.0.0", deps: ["a", "keeper"] },
    reg({ name: "a", version: "1.3.0", deps: ["b 2.0.1"] }),
    reg({ name: "keeper", version: "3.1.0", deps: ["b 1.4.0"] }),
    reg({ name: "b", version: "1.4.0" }),
    reg({ name: "b", version: "2.0.1" }),
  ]);
  const state = { text: before };
  const { result, cargo } = runUpdate(
    state,
    { updated: after, onPrecise: () => before },
    {
      a: { versions: [{ vers: "1.2.0" }, { vers: "1.3.0" }], dates: { "1.3.0": OLD_DATE } },
      b: { versions: [{ vers: "1.4.0" }, { vers: "2.0.1" }], dates: { "2.0.1": OLD_DATE } },
    },
  );
  const report = await result;
  assert.deepEqual(report.blocking, []);
  assert.deepEqual(cargo.calls, ["update", "update a@1.3.0 --precise 1.2.0"]);
  assert.deepEqual(report.changes, []);
  assert.equal(report.crossings.length, 1);
  assert.equal(report.crossings[0].dragged.name, "b");
  assert.equal(report.crossings[0].dragged.from, "1.4.0");
});

test("dual renamed edges to one crate are not misread as a crossing", async () => {
  // `a` depends on b 1.x AND b 2.x at once (renamed dependencies). An
  // unrelated package moves; the dual edges hold still. A by-name edge map
  // would drop one of them and report a phantom 2→1 crossing here.
  const dual = (o) => [
    { name: "app", version: "0.0.0", deps: ["a", "other"] },
    reg({ name: "a", version: "1.0.0", deps: ["b 1.0.0", "b 2.0.0"] }),
    reg({ name: "b", version: "1.0.0" }),
    reg({ name: "b", version: "2.0.0" }),
    reg({ name: "other", version: o }),
  ];
  const state = { text: renderLock(dual("3.1.0")) };
  const { result, cargo } = runUpdate(
    state,
    { updated: renderLock(dual("3.2.0")) },
    { other: { versions: [{ vers: "3.1.0" }, { vers: "3.2.0" }], dates: { "3.2.0": OLD_DATE } } },
  );
  const report = await result;
  assert.deepEqual(report.blocking, []);
  assert.deepEqual(report.crossings, []);
  assert.deepEqual(cargo.calls, ["update"]);
  assert.deepEqual(report.changes.map((c) => c.name), ["other"]);
});

test("a crossing among dual edges is still caught and unwound", async () => {
  // The same dual-edge dependent bumps and its b 2.x edge moves to 3.x
  // while the 1.x edge stays: group 2 lost, group 3 gained — a crossing.
  const before = renderLock([
    APP,
    reg({ name: "a", version: "1.0.0", deps: ["b 1.0.0", "b 2.0.0"] }),
    reg({ name: "b", version: "1.0.0" }),
    reg({ name: "b", version: "2.0.0" }),
  ]);
  const after = renderLock([
    APP,
    reg({ name: "a", version: "1.1.0", deps: ["b 1.0.0", "b 3.0.0"] }),
    reg({ name: "b", version: "1.0.0" }),
    reg({ name: "b", version: "3.0.0" }),
  ]);
  const state = { text: before };
  const { result, cargo } = runUpdate(
    state,
    { updated: after, onPrecise: () => before },
    {
      a: { versions: [{ vers: "1.0.0" }, { vers: "1.1.0" }], dates: { "1.1.0": OLD_DATE } },
      b: { versions: [{ vers: "1.0.0" }, { vers: "2.0.0" }, { vers: "3.0.0" }], dates: {} },
    },
  );
  const report = await result;
  assert.deepEqual(report.blocking, []);
  assert.deepEqual(cargo.calls, ["update", "update a@1.1.0 --precise 1.0.0"]);
  assert.equal(report.crossings.length, 1);
  assert.equal(report.crossings[0].dragged.from, "2.0.0");
  assert.equal(report.crossings[0].dragged.to, "3.0.0");
});

test("a pin that removes a freshly-added young transitive does not block on it", async () => {
  // a's young bump brought brand-new (also young, only release). Pinning a
  // back removes brand-new from the graph — judged on the stale diff, the
  // orphaned entry would block the whole batch; one pin per round with a
  // re-parse must let the batch settle cleanly instead.
  const before = renderLock([APP, reg({ name: "a", version: "1.2.0" })]);
  const after = renderLock([
    APP,
    reg({ name: "a", version: "1.2.5", deps: ["brand-new"] }),
    reg({ name: "brand-new", version: "0.1.0" }),
  ]);
  const state = { text: before };
  const { result, cargo } = runUpdate(
    state,
    { updated: after, onPrecise: () => renderLock([APP, reg({ name: "a", version: "1.2.4" })]) },
    {
      a: {
        versions: [{ vers: "1.2.0" }, { vers: "1.2.4" }, { vers: "1.2.5" }],
        dates: { "1.2.5": FRESH_DATE, "1.2.4": OLD_DATE },
      },
      "brand-new": { versions: [{ vers: "0.1.0" }], dates: { "0.1.0": FRESH_DATE } },
    },
  );
  const report = await result;
  assert.deepEqual(report.blocking, []);
  assert.deepEqual(cargo.calls, ["update", "update a@1.2.5 --precise 1.2.4"]);
  assert.deepEqual(report.changes, [{ name: "a", from: "1.2.0", to: "1.2.4", direct: true }]);
});

test("a registry pin is source-qualified when a git copy shares the ID", async () => {
  const g = "git+https://github.com/x/dupe?rev=x#abc1234";
  const at = (crates) =>
    renderLock([
      {
        name: "app",
        version: "0.0.0",
        deps: [`dupe ${crates} (${CRATES_IO_SOURCE})`, `dupe 2.0.5 (${g})`],
      },
      reg({ name: "dupe", version: crates }),
      { name: "dupe", version: "2.0.5", source: g },
    ]);
  const state = { text: at("2.0.0") };
  const { result, cargo } = runUpdate(
    state,
    // The updated lockfile shares name+version with the git copy; the pin
    // rewrites the dependent's reference too, as real cargo does.
    { updated: at("2.0.5"), onPrecise: () => at("2.0.4") },
    {
      dupe: {
        versions: [{ vers: "2.0.0" }, { vers: "2.0.4" }, { vers: "2.0.5" }],
        dates: { "2.0.5": FRESH_DATE, "2.0.4": OLD_DATE },
      },
    },
  );
  const report = await result;
  assert.deepEqual(report.blocking, []);
  assert.deepEqual(cargo.calls, [
    "update",
    `update ${CRATES_IO_SOURCE}#dupe@2.0.5 --precise 2.0.4`,
  ]);
  assert.deepEqual(report.changes.map((c) => `${c.from}->${c.to}`), ["2.0.0->2.0.4"]);
});

test("held majors and requirement-held compatibles are reported for direct deps", async () => {
  const text = renderLock([APP, reg({ name: "a", version: "1.2.0" })]);
  const state = { text };
  const { result } = runUpdate(
    state,
    { updated: text }, // cargo takes nothing: the manifest pins exactly
    {
      a: {
        versions: [{ vers: "1.2.0" }, { vers: "1.2.9" }, { vers: "2.1.0" }, { vers: "3.0.0-beta.1" }],
        dates: { "1.2.9": OLD_DATE },
      },
    },
  );
  const report = await result;
  // 2.1.0 is the newest STABLE major — the beta never counts.
  assert.deepEqual(report.held, [{ name: "a", current: "1.2.0", newest: "2.1.0" }]);
  assert.deepEqual(report.requirementHeld, [{ name: "a", current: "1.2.0", newest: "1.2.9" }]);
  const md = reportMarkdown(report);
  assert.match(md, /needs a deliberate migration/);
  assert.match(md, /manifest's requirement/);
});

test("an untaken compatible that is merely cooling is reported as cooldown, not requirement", async () => {
  const text = renderLock([APP, reg({ name: "a", version: "1.2.0" })]);
  const state = { text };
  const { result } = runUpdate(
    state,
    { updated: text },
    { a: { versions: [{ vers: "1.2.0" }, { vers: "1.2.9" }], dates: { "1.2.9": FRESH_DATE } } },
  );
  const report = await result;
  assert.deepEqual(report.requirementHeld, []);
  assert.equal(report.cooldown.length, 1);
  assert.equal(report.cooldown[0].name, "a");
  assert.equal(report.cooldown[0].to, null);
});

test("a git dependency cargo update moved is restored to its committed revision", async () => {
  const gitOld = "git+https://github.com/example/vendored?branch=main#aaaa111";
  const gitNew = "git+https://github.com/example/vendored?branch=main#bbbb222";
  const at = (source, a) =>
    renderLock([
      { name: "app", version: "0.0.0", deps: ["vendored", "a"] },
      { name: "vendored", version: "0.3.0", source },
      reg({ name: "a", version: a }),
    ]);
  const state = { text: at(gitOld, "1.2.0") };
  const { result, cargo } = runUpdate(
    state,
    {
      updated: at(gitNew, "1.2.5"), // the branch advanced; cargo took the new rev
      onPrecise: (name, _at, _to, text) => text.replace(gitNew, gitOld),
    },
    { a: { versions: [{ vers: "1.2.0" }, { vers: "1.2.5" }], dates: { "1.2.5": OLD_DATE } } },
  );
  const report = await result;
  assert.deepEqual(report.blocking, []);
  assert.deepEqual(cargo.calls, [
    "update",
    "update git+https://github.com/example/vendored?branch=main#vendored@0.3.0 --precise aaaa111",
  ]);
  assert.deepEqual(report.changes, [{ name: "a", from: "1.2.0", to: "1.2.5", direct: true }]);
  assert.match(report.unmanaged.join("\n"), /vendored.*restored to aaaa111/);
});

test("diffLockfiles keeps same-version packages from different sources apart", () => {
  // Renamed dependencies can pull the same crate name at compatible
  // versions from two different git repositories — a valid graph, not the
  // duplicate the one-source rule refuses.
  const g = (repo, frag) => `git+https://github.com/${repo}/dupe?rev=x#${frag}`;
  const lock = parseLockfile(
    renderLock([
      { name: "app", version: "0.0.0", deps: [`dupe 1.2.3 (${g("x", "111")})`, `dupe 1.2.3 (${g("y", "222")})`] },
      { name: "dupe", version: "1.2.3", source: g("x", "111") },
      { name: "dupe", version: "1.2.3", source: g("y", "222") },
    ]),
  );
  const diff = diffLockfiles(lock, lock);
  assert.deepEqual(diff.errors, []);
  assert.equal(diff.unchanged.length, 3);
});

test("a pre-release pin cargo update promoted is restored", async () => {
  const at = (v) =>
    renderLock([{ name: "app", version: "0.0.0", deps: ["shiny"] }, reg({ name: "shiny", version: v })]);
  const state = { text: at("2.0.0-rc.1") };
  const { result, cargo } = runUpdate(
    state,
    { updated: at("2.0.0") }, // cargo promoted the pin to the new stable
    { shiny: { versions: [{ vers: "2.0.0-rc.1" }, { vers: "2.0.0" }], dates: { "2.0.0": OLD_DATE } } },
  );
  const report = await result;
  assert.deepEqual(report.blocking, []);
  assert.deepEqual(cargo.calls, ["update", "update shiny@2.0.0 --precise 2.0.0-rc.1"]);
  assert.deepEqual(report.changes, []);
  assert.match(report.unmanaged.join("\n"), /pre-release pin.*restored to 2\.0\.0-rc\.1/);
});

test("a stable pin cargo update moved onto a pre-release is restored", async () => {
  // A requirement that names a pre-release admits it (">=1.2, <1.4.0-z"
  // matches 1.4.0-alpha.1), so cargo can move a stable pin onto one
  // within its compatibility group; the batch declines the move.
  const at = (v) => renderLock([APP, reg({ name: "a", version: v })]);
  const state = { text: at("1.2.0") };
  const { result, cargo } = runUpdate(
    state,
    { updated: at("1.4.0-alpha.1") },
    { a: { versions: [{ vers: "1.2.0" }, { vers: "1.4.0-alpha.1" }], dates: {} } },
  );
  const report = await result;
  assert.deepEqual(report.blocking, []);
  assert.deepEqual(cargo.calls, ["update", "update a@1.4.0-alpha.1 --precise 1.2.0"]);
  assert.deepEqual(report.changes, []);
});

test("a stable pin dragged across its compatibility group onto a pre-release is restored", async () => {
  // ">=1.0, <2.0.0-beta" admits 2.0.0-alpha.1, a different compat group
  // from 1.2.3 — the diff reads that as a removal plus an arrival, so the
  // arrival is what gets pinned back to the version it displaced.
  const at = (v) => renderLock([APP, reg({ name: "a", version: v })]);
  const state = { text: at("1.2.3") };
  const { result, cargo } = runUpdate(
    state,
    { updated: at("2.0.0-alpha.1") },
    { a: { versions: [{ vers: "1.2.3" }, { vers: "2.0.0-alpha.1" }], dates: {} } },
  );
  const report = await result;
  assert.deepEqual(report.blocking, []);
  assert.deepEqual(cargo.calls, ["update", "update a@2.0.0-alpha.1 --precise 1.2.3"]);
  assert.deepEqual(report.changes, []);
  assert.deepEqual(report.added, []);
  assert.deepEqual(report.removed, []);
});

test("a pre-release arrival with no displaced version blocks the run", async () => {
  const before = renderLock([APP, reg({ name: "a", version: "1.2.0" })]);
  const after = renderLock([
    APP,
    reg({ name: "a", version: "1.2.5", deps: ["b"] }),
    reg({ name: "b", version: "0.1.0-beta.1" }),
  ]);
  const state = { text: before };
  const { result } = runUpdate(
    state,
    { updated: after },
    {
      a: { versions: [{ vers: "1.2.0" }, { vers: "1.2.5" }], dates: { "1.2.5": OLD_DATE } },
      b: { versions: [{ vers: "0.1.0-beta.1" }], dates: { "0.1.0-beta.1": OLD_DATE } },
    },
  );
  const report = await result;
  assert.ok(report.blocking.some((b) => /b 0\.1\.0-beta\.1 arrived as a pre-release/.test(b)));
  assert.ok(report.blocking.some((b) => /no removed b exists to restore/.test(b)));
});

test("a blocking judgment against a pre-pin graph is discarded once a pin lands", async () => {
  // b (young, only release) sorts before y in the added list and would
  // block — but pinning y back removes b from the graph entirely, so the
  // stale judgment must not survive the round.
  const before = renderLock([APP, reg({ name: "a", version: "1.2.0" })]);
  const after = renderLock([
    APP,
    reg({ name: "a", version: "1.2.5", deps: ["y"] }),
    reg({ name: "b", version: "0.9.0" }),
    reg({ name: "y", version: "3.1.0", deps: ["b"] }),
  ]);
  const settled = renderLock([
    APP,
    reg({ name: "a", version: "1.2.5", deps: ["y"] }),
    reg({ name: "y", version: "3.0.0" }),
  ]);
  const state = { text: before };
  const { result, cargo } = runUpdate(
    state,
    { updated: after, onPrecise: () => settled },
    {
      a: { versions: [{ vers: "1.2.0" }, { vers: "1.2.5" }], dates: { "1.2.5": OLD_DATE } },
      b: { versions: [{ vers: "0.9.0" }], dates: { "0.9.0": FRESH_DATE } },
      y: {
        versions: [{ vers: "3.0.0" }, { vers: "3.1.0" }],
        dates: { "3.0.0": OLD_DATE, "3.1.0": FRESH_DATE },
      },
    },
  );
  const report = await result;
  assert.deepEqual(report.blocking, []);
  assert.ok(cargo.calls.includes("update y@3.1.0 --precise 3.0.0"));
  assert.deepEqual(report.added.map((p) => `${p.name} ${p.version}`), ["y 3.0.0"]);
});

test("a git branch advance that crossed a compatibility group is restored", async () => {
  // The diff reads a 1.x -> 2.x git refresh as a removal plus an arrival,
  // so the arrival pass is what pins it back to the committed revision.
  const gitOld = "git+https://github.com/example/vendored?branch=main#aaaa111";
  const gitNew = "git+https://github.com/example/vendored?branch=main#bbbb222";
  const at = (source, v) =>
    renderLock([
      { name: "app", version: "0.0.0", deps: ["vendored"] },
      { name: "vendored", version: v, source },
    ]);
  const state = { text: at(gitOld, "1.3.0") };
  const { result, cargo } = runUpdate(
    state,
    { updated: at(gitNew, "2.0.0"), onPrecise: () => at(gitOld, "1.3.0") },
    {},
  );
  const report = await result;
  assert.deepEqual(report.blocking, []);
  assert.deepEqual(cargo.calls, [
    "update",
    "update git+https://github.com/example/vendored?branch=main#vendored@2.0.0 --precise aaaa111",
  ]);
  assert.deepEqual(report.changes, []);
  assert.match(report.unmanaged.join("\n"), /vendored.*restored to aaaa111/);
});

test("renamed path dependencies at compatible versions are a valid graph", async () => {
  // Two sourceless path packages share a name at compatible versions —
  // path deps pin exactly, with no range for the resolver to unify — so
  // neither the diff nor the edge walk may refuse the baseline.
  const at = (a) =>
    renderLock([
      { name: "app", version: "0.0.0", deps: ["foo 1.2.0", "foo 1.3.0", "a"] },
      { name: "foo", version: "1.2.0" },
      { name: "foo", version: "1.3.0" },
      reg({ name: "a", version: a }),
    ]);
  const diff = diffLockfiles(parseLockfile(at("1.2.0")), parseLockfile(at("1.2.0")));
  assert.deepEqual(diff.errors, []);
  assert.equal(diff.unchanged.length, 4);
  const state = { text: at("1.2.0") };
  const { result } = runUpdate(
    state,
    { updated: at("1.2.5") },
    { a: { versions: [{ vers: "1.2.0" }, { vers: "1.2.5" }], dates: { "1.2.5": OLD_DATE } } },
  );
  const report = await result;
  assert.deepEqual(report.blocking, []);
  assert.deepEqual(report.changes, [{ name: "a", from: "1.2.0", to: "1.2.5", direct: true }]);
});

test("git dependencies and pre-release pins are reported unmanaged, never touched", async () => {
  const gitPkg = {
    name: "vendored",
    version: "0.3.0",
    source: "git+https://github.com/example/vendored?rev=abc123#abc123",
    checksum: undefined,
  };
  const text = renderLock([
    { name: "app", version: "0.0.0", deps: ["vendored", "shiny"] },
    { ...gitPkg },
    reg({ name: "shiny", version: "2.0.0-rc.1" }),
  ]);
  const state = { text };
  const { result, net } = runUpdate(state, { updated: text }, {
    shiny: { versions: [{ vers: "2.0.0-rc.1" }], dates: {} },
    vendored: { versions: [{ vers: "0.3.0" }], dates: {} },
  });
  const report = await result;
  assert.deepEqual(report.blocking, []);
  assert.equal(report.unmanaged.length, 2);
  assert.match(report.unmanaged[0], /not crates\.io/);
  assert.match(report.unmanaged[1], /pre-release pin/);
  // The git package's "registry" is never asked about.
  assert.ok(!net.requests.some((u) => u.includes("vendored") && u.startsWith(INDEX_URL)));
});

test("an unreadable index lands in errors and holds only its own crate", async () => {
  const state = { text: renderLock([APP, reg({ name: "a", version: "1.2.0" })]) };
  const { result } = runUpdate(
    state,
    { updated: renderLock([APP, reg({ name: "a", version: "1.2.5" })]) },
    { a: { versions: [{ vers: "1.2.0" }, { vers: "1.2.5" }], dates: { "1.2.5": OLD_DATE } } },
    { indexUrl: "https://index.invalid" }, // every index fetch will throw
  );
  const report = await result;
  assert.ok(report.errors.length > 0);
  // The bump itself survives — the cooldown was satisfiable from the API
  // alone; only the held/requirement reporting lost its source.
  assert.deepEqual(report.changes, [{ name: "a", from: "1.2.0", to: "1.2.5", direct: true }]);
});

test("cargo update failing is a thrown error, not a quiet no-op", async () => {
  const state = { text: renderLock([APP, reg({ name: "a", version: "1.2.0" })]) };
  const cargo = { runCargo: () => ({ ok: false, output: "error: registry down" }) };
  await assert.rejects(
    updateLockfile({
      readLockfile: () => state.text,
      runCargo: cargo.runCargo,
      fetcher: makeFetcher({}).fetcher,
      now: NOW,
    }),
    /cargo update failed/,
  );
});

test("a zero cooldown never asks for dates and attributes misses to the requirement", async () => {
  const text = renderLock([APP, reg({ name: "a", version: "1.2.0" })]);
  const state = { text };
  const { result, net } = runUpdate(
    state,
    { updated: text },
    { a: { versions: [{ vers: "1.2.0" }, { vers: "1.2.9" }], dates: {} } },
    { cooldownDays: 0 },
  );
  const report = await result;
  assert.deepEqual(report.requirementHeld, [{ name: "a", current: "1.2.0", newest: "1.2.9" }]);
  assert.ok(!net.requests.some((u) => u.startsWith(API_URL)));
});

test("reportMarkdown says so when nothing moved", () => {
  const empty = {
    changes: [], added: [], removed: [], held: [], crossings: [],
    cooldown: [], requirementHeld: [], unmanaged: [], errors: [], blocking: [],
  };
  assert.match(reportMarkdown(empty), /No dependency updates available this run\./);
});

// ---------------------------------------------------------------------------
// The hardened fetcher, against a stubbed global fetch.
// ---------------------------------------------------------------------------

const withFetch = async (impl, run) => {
  const real = globalThis.fetch;
  globalThis.fetch = impl;
  try {
    return await run();
  } finally {
    globalThis.fetch = real;
  }
};

test("httpsFetcher follows https redirects and refuses an http hop", async () => {
  const hops = [];
  await withFetch(
    async (url) => {
      hops.push(url);
      if (url === "https://a.example/x") {
        return { status: 302, headers: new Map([["location", "https://b.example/y"]]) };
      }
      return { status: 200, ok: true, headers: new Map() };
    },
    async () => {
      const res = await httpsFetcher("https://a.example/x");
      assert.equal(res.status, 200);
      assert.deepEqual(hops, ["https://a.example/x", "https://b.example/y"]);
    },
  );
  await withFetch(
    async () => ({ status: 302, headers: new Map([["location", "http://evil.example/"]]) }),
    () =>
      assert.rejects(httpsFetcher("https://a.example/x"), /redirected off https/),
  );
});

test("httpsFetcher caps the redirect chain", async () => {
  await withFetch(
    async (url) => ({
      status: 302,
      headers: new Map([["location", url + "0"]]),
    }),
    () => assert.rejects(httpsFetcher("https://a.example/x"), /too many redirects/),
  );
});

test("operator-plus-wildcard requirements are partial versions, as Cargo reads them", () => {
  assert.equal(reqMatches(">=1.*", "1.0.0"), true);
  assert.equal(reqMatches(">=1.*", "0.9.0"), false);
  assert.equal(reqMatches("^1.2.*", "1.9.0"), true);
  assert.equal(reqMatches("<=1.2.*", "1.2.9"), true);
  assert.equal(reqMatches("<=1.2.*", "1.3.0"), false);
  assert.equal(reqMatches(">=*", "1.0.0"), null);
  assert.equal(reqMatches("1.*.2", "1.0.2"), null);
});
